### ISSUE TITLE
shen_ISMB2014.py issue with different fgtree_folder

### ISSUE THREAD

**Issue by tobigithub** [icdishb/fingerid#5]
Hi,
running the standard test example in shen_ISMB2014.py  is fine, changing the input to "metlin_trees" will run for a while and then create the following error below. So I guess I am missing the correct training cases and structures and or some other parameters. Its not readily visible to me which parameters have to be changed in shen_ISMB2014.py if I use different spectra, or is that something that has to be changed in another script?

````R
    # Set data info, default run on a small 50 compounds dataset.
    # To run the 978 componds dataset, change fgtree_folder to "metlin_trees".
    # The MS/MS used in the paper can be downloaded from METLIN database
    # with the same metlin id used in the filenames of fgtrees.
    # fgtree_folder = "test_data/train_trees/"

    fgtree_folder = "metlin_trees"
    ms_folder = "test_data/train_ms/"
    fingerprints = "test_data/train_output.txt" # output we want to predict
````

It will run for a while and then just end like this.

````R
~/fingerid/examples$ python shen_ISMB2014.py 
computing kernel PPK
computing kernel NB
computing kernel NI
computing kernel LB
computing kernel LC
computing kernel CPC
computing kernel CP2
computing kernel CPK
computing kernel LI
computing kernel CSC
computing kernel RLB
computing kernel RLI
computing train kernel for 0'th example
computing train kernel for 1'th example
computing train kernel for 2'th example
computing train kernel for 3'th example
computing train kernel for 4'th example
computing train kernel for 5'th example
computing train kernel for 6'th example
computing train kernel for 7'th example
computing train kernel for 8'th example
computing train kernel for 9'th example
computing train kernel for 10'th example
computing train kernel for 11'th example
computing train kernel for 12'th example
computing train kernel for 13'th example
computing train kernel for 14'th example
computing train kernel for 15'th example
computing train kernel for 16'th example
computing train kernel for 17'th example
computing train kernel for 18'th example
computing train kernel for 19'th example
computing train kernel for 20'th example
computing train kernel for 21'th example
computing train kernel for 22'th example
computing train kernel for 23'th example
computing train kernel for 24'th example
computing train kernel for 25'th example
computing train kernel for 26'th example
computing train kernel for 27'th example
computing train kernel for 28'th example
computing train kernel for 29'th example
computing train kernel for 30'th example
computing train kernel for 31'th example
computing train kernel for 32'th example
computing train kernel for 33'th example
computing train kernel for 34'th example
computing train kernel for 35'th example
computing train kernel for 36'th example
computing train kernel for 37'th example
computing train kernel for 38'th example
computing train kernel for 39'th example
computing train kernel for 40'th example
computing train kernel for 41'th example
computing train kernel for 42'th example
computing train kernel for 43'th example
computing train kernel for 44'th example
computing train kernel for 45'th example
computing train kernel for 46'th example
computing train kernel for 47'th example
computing train kernel for 48'th example
computing train kernel for 49'th example
Writing PPK kernel to PPK_kernel.txt
Writing LB kernel to LB_kernel.txt
Writing NB kernel to NB_kernel.txt
Writing LC kernel to LC_kernel.txt
Writing RLB kernel to RLB_kernel.txt
Writing NI kernel to NI_kernel.txt
Writing LI kernel to LI_kernel.txt
Writing RLI kernel to RLI_kernel.txt
Writing CP2 kernel to CP2_kernel.txt
Writing CPC kernel to CPC_kernel.txt
Writing CSC kernel to CSC_kernel.txt
Writing CPK kernel to CPK_kernel.txt

Train SVM for kernel PPK
cv on 0'th fingerprint
cv on 1'th fingerprint
cv on 2'th fingerprint
cv on 3'th fingerprint
cv on 4'th fingerprint
cv on 5'th fingerprint
cv on 6'th fingerprint
cv on 7'th fingerprint
cv on 8'th fingerprint
cv on 9'th fingerprint
Writting prediction in cvpred_PPK.txt
Train SVM for kernel NB
cv on 0'th fingerprint
cv on 1'th fingerprint
cv on 2'th fingerprint
cv on 3'th fingerprint
cv on 4'th fingerprint
cv on 5'th fingerprint
cv on 6'th fingerprint
cv on 7'th fingerprint
cv on 8'th fingerprint
cv on 9'th fingerprint
Traceback (most recent call last):
  File "shen_ISMB2014.py", line 119, in <module>
    trainSVM(km_f, fingerprints, np=16, c_sel=True)
  File "shen_ISMB2014.py", line 91, in trainSVM
    cvpreds = internalCV_mp(train_km, labels, 5, select_c=c_sel, n_p=np, prob=prob)
  File "../../fingerid/fingerid/model/internalCV_mp.py", line 83, in internalCV_mp
    pred_fp[:,fp_ind] = res.pred_fp_
ValueError: could not broadcast input array from shape (978) into shape (50)


````
Cheers
Tobias

**Comment by icdishb** [comment]
Hi, our problem is that we don't have the right to give metlin mass spectra out. You may need to download the MS/MS from metlin (require purchase) you self. We name the trees in the metlin_trees folder by the metlin identifier. So if you download the spectra which have the same id as the trees, then change the ms_folder accordingly, you should be able to start your own experiment. Notice, currently the data included in this package is just for demo use. You may also need to regenerate the fingerprints and change the fingerprints file path accordingly.

**Comment by tobigithub** [comment]
Hi,
thanks, OK got it,  I actually want to use public spectra from MONA,
http://mona.fiehnlab.ucdavis.edu/spectra/querytree

There are around LC-MS/MS 26,000 spectra in MSP format (ASCII), so how can I create the 
tree files (*.dot) for all these compounds, is that done in the parser?

Tobias

**Comment by icdishb** [comment]
Hi, you can use [Sirius](https://bio.informatik.uni-jena.de/software/sirius/) to compute the trees. 26,000 is a lot... It may take weeks to finish. The parser now can only parse mass spectra in massbank format, metlin format and the format used in the examples, more detail can be found in readme file. Also, the Sirius now may give you json format. In this case, new parser will be needed. 

Huibin

**Comment by tobigithub** [comment]
Hi,
thanks, so I can use sirius.exe or sirius.jar to calculate trees from the MassBank, MONA or GNPS spectra like this if I want the dot files:
````R
sirius  -c 1 --ppm-max 2.0  -o trees -O dot  connecticut_001.ms
`````
Speed, actually I can compute around 1000 MS/MS spectra in 2 minutes, by using a parallel batch process, so 20,000 spectra will take roughly 40 minutes (32 thread workstation). There are however few compounds that are not "compatible" and will either break Sirius or it will simply take too long for a given parameter set (average speed per compound is a few seconds).

I also see of course one problem, that one would need to validate that the Sirius formula and trees are correct for these reference spectra (depending on the mass accuracy and its only MS/MS they can be off). I think also the MassBank and GNPS spectra for CSI:FIngerID are published here
https://bio.informatik.uni-jena.de/data/ So that could be a good starter set too.

I wonder if there could be a somewhat more detailed workflow description how FingerID actually can be used with new spectra:
1) acquire MS/MS spectra from MassBank, MONA, GNPS
2) Format to SIrius readable format 
3) Call sirius  -c 1 --ppm-max 2.0  -o trees -O dot  example.ms
4) Create structure database with SDF files
5) Use OpenBabel and fpgenerator.py to generate fingerprints
6) How to search the compounds from fingerprint data
7) How to generate hit lists with scores for the candidates

Right now many of the critical and required steps are missing and for practitioners it is almost impossible to use, unless you have detailed programming knowledge, but I surely can see many use cases, based on the published performance of FIngerID so it would be really useful to actually apply and use it for example with new spectra and larger training databases. 

Cheers
Tobias

**Comment by icdishb** [comment]
Hi Tobias, thanks for the great advice, I will add this workflow to the readme in the future. To start running FingerID indeed takes too much work. May be I should add the link to CSI:fingerid, where the web server is running.
